services:
  postgres_dev:
    image: postgres
    container_name: land_postgres_dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: land
    ports:
      - '5400:5432'
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  postgres_test:
    image: postgres
    container_name: land_postgres_test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: land_test
    ports:
      - '5401:5432'
    volumes:
      - pg_data_test:/var/lib/postgresql/data

volumes:
  pg_data_dev:
  pg_data_test:
