services:
  db:
    image: postgres
    container_name: land_postgres_test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: land
    ports:
      - '5400:5432'
